---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Themes
- type: directory
  path: content/themes
  label: Themes
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: content/ssg
  label: SSG
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: content/cms
  label: CMS
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: content/css
  label: CSS
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: content/category
  label: Category
  create: documents
  match: "*"
  exclude: _index.md
upload_dir: public/blog
public_path: "/blog"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
